/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author camilotr
 */
public class HistorialGUI extends javax.swing.JFrame {

    /**
     * Creates new form HistorialGUI
     */
    public HistorialGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTfTiempoTerminacion = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbl_historicoProceso = new javax.swing.JLabel();
        jbl_canProceso = new javax.swing.JLabel();
        jbl_timeProcesos = new javax.swing.JLabel();
        jtf_canProceso = new javax.swing.JTextField();
        jtf_TiempoEspera = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_historicoProcesos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTfTiempoTerminacion.setEditable(false);
        jTfTiempoTerminacion.setBackground(new java.awt.Color(225, 225, 237));
        jTfTiempoTerminacion.setBorder(null);
        jTfTiempoTerminacion.setEnabled(false);
        jTfTiempoTerminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfTiempoTerminacionActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(225, 225, 237));
        jTextField1.setBorder(null);
        jTextField1.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Tiempo promedio terminación del proceso:");

        jbl_historicoProceso.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jbl_historicoProceso.setForeground(new java.awt.Color(255, 255, 0));
        jbl_historicoProceso.setText("Historico Procesos");

        jbl_canProceso.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jbl_canProceso.setForeground(new java.awt.Color(0, 0, 204));
        jbl_canProceso.setText("Cantidad De Procesos:");

        jbl_timeProcesos.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jbl_timeProcesos.setForeground(new java.awt.Color(255, 0, 0));
        jbl_timeProcesos.setText("Tiempo de espera: ");

        jtf_canProceso.setEditable(false);
        jtf_canProceso.setBackground(new java.awt.Color(225, 225, 237));
        jtf_canProceso.setBorder(null);
        jtf_canProceso.setEnabled(false);
        jtf_canProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_canProcesoActionPerformed(evt);
            }
        });

        jtf_TiempoEspera.setEditable(false);
        jtf_TiempoEspera.setBackground(new java.awt.Color(225, 225, 237));
        jtf_TiempoEspera.setBorder(null);
        jtf_TiempoEspera.setEnabled(false);
        jtf_TiempoEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_TiempoEsperaActionPerformed(evt);
            }
        });

        jt_historicoProcesos.setForeground(new java.awt.Color(231, 209, 209));
        jt_historicoProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#Proceso", "Nombre", "Ragafa", "Quantum", "Tiempo Final", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_historicoProcesos.setEnabled(false);
        jScrollPane2.setViewportView(jt_historicoProcesos);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("Tiempo de terminación de los procesos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbl_canProceso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3))
                                        .addComponent(jbl_timeProcesos))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtf_canProceso)
                                        .addComponent(jTfTiempoTerminacion)
                                        .addComponent(jTextField1)
                                        .addComponent(jtf_TiempoEspera)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jbl_historicoProceso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(94, 94, 94))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jbl_historicoProceso)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbl_canProceso)
                                .addComponent(jtf_canProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jTfTiempoTerminacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbl_timeProcesos)
                        .addComponent(jtf_TiempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfTiempoTerminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfTiempoTerminacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfTiempoTerminacionActionPerformed

    private void jtf_canProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_canProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_canProcesoActionPerformed

    private void jtf_TiempoEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_TiempoEsperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_TiempoEsperaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTfTiempoTerminacion;
    private javax.swing.JLabel jbl_canProceso;
    private javax.swing.JLabel jbl_historicoProceso;
    private javax.swing.JLabel jbl_timeProcesos;
    public javax.swing.JTable jt_historicoProcesos;
    public javax.swing.JTextField jtf_TiempoEspera;
    public javax.swing.JTextField jtf_canProceso;
    // End of variables declaration//GEN-END:variables
}
