/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author camilotr
 */
public class ProcesarGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProcesarGUI
     */
    public ProcesarGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollbar1 = new java.awt.Scrollbar();
        jlb_nombreP = new javax.swing.JLabel();
        jbl_ragafaCPU = new javax.swing.JLabel();
        jtf_nombreP = new javax.swing.JTextField();
        jbt_agregar = new javax.swing.JButton();
        jbt_iniciar = new javax.swing.JButton();
        jbl_lisProcesos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_lisProcesos = new javax.swing.JTable();
        jbl_proProceso = new javax.swing.JLabel();
        jbl_porcentaje = new javax.swing.JLabel();
        jbl_progreso = new javax.swing.JLabel();
        jtf_proProceso = new javax.swing.JTextField();
        jtf_porcentaje = new javax.swing.JTextField();
        jBarraProgreso = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        jbl_canProceso = new javax.swing.JLabel();
        jbl_timeProcesos = new javax.swing.JLabel();
        jtf_canProceso = new javax.swing.JTextField();
        jtf_TiempoEspera = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_historicoProcesos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTfTiempoTerminacion = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSRafaCPU = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Round Robin");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);

        jlb_nombreP.setText("Nombre del proceso");

        jbl_ragafaCPU.setText("Rafaga del CPU (Máximo 12)");

        jtf_nombreP.setBackground(new java.awt.Color(225, 225, 237));
        jtf_nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombrePActionPerformed(evt);
            }
        });

        jbt_agregar.setBackground(new java.awt.Color(251, 245, 245));
        jbt_agregar.setForeground(new java.awt.Color(0, 0, 153));
        jbt_agregar.setText("Agregar");
        jbt_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbt_agregarMousePressed(evt);
            }
        });

        jbt_iniciar.setBackground(new java.awt.Color(251, 245, 245));
        jbt_iniciar.setForeground(new java.awt.Color(153, 0, 0));
        jbt_iniciar.setText("Iniciar");

        jbl_lisProcesos.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jbl_lisProcesos.setForeground(new java.awt.Color(0, 0, 153));
        jbl_lisProcesos.setText("Lista De Procesos");

        jtb_lisProcesos.setBackground(new java.awt.Color(255, 245, 243));
        jtb_lisProcesos.setForeground(new java.awt.Color(243, 227, 227));
        jtb_lisProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#Proceso", "Nombre", "Rafaga", "Quantum", "Residuo rafaga", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb_lisProcesos.setEnabled(false);
        jScrollPane1.setViewportView(jtb_lisProcesos);
        if (jtb_lisProcesos.getColumnModel().getColumnCount() > 0) {
            jtb_lisProcesos.getColumnModel().getColumn(0).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(1).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(2).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(3).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(4).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(5).setResizable(false);
        }

        jbl_proProceso.setText("Proceso");

        jbl_porcentaje.setText("Porcentaje");

        jbl_progreso.setText("Progreso");

        jtf_proProceso.setEditable(false);
        jtf_proProceso.setBackground(new java.awt.Color(255, 204, 204));
        jtf_proProceso.setEnabled(false);

        jtf_porcentaje.setEditable(false);
        jtf_porcentaje.setBackground(new java.awt.Color(255, 204, 204));
        jtf_porcentaje.setEnabled(false);

        jBarraProgreso.setForeground(new java.awt.Color(0, 255, 0));
        jBarraProgreso.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Historico Procesos");

        jbl_canProceso.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jbl_canProceso.setForeground(new java.awt.Color(0, 0, 204));
        jbl_canProceso.setText("Cantidad De Procesos:");

        jbl_timeProcesos.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jbl_timeProcesos.setForeground(new java.awt.Color(255, 0, 0));
        jbl_timeProcesos.setText("Tiempo de espera: ");

        jtf_canProceso.setEditable(false);
        jtf_canProceso.setBackground(new java.awt.Color(225, 225, 237));
        jtf_canProceso.setBorder(null);
        jtf_canProceso.setEnabled(false);
        jtf_canProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_canProcesoActionPerformed(evt);
            }
        });

        jtf_TiempoEspera.setEditable(false);
        jtf_TiempoEspera.setBackground(new java.awt.Color(225, 225, 237));
        jtf_TiempoEspera.setBorder(null);
        jtf_TiempoEspera.setEnabled(false);
        jtf_TiempoEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_TiempoEsperaActionPerformed(evt);
            }
        });

        jt_historicoProcesos.setForeground(new java.awt.Color(231, 209, 209));
        jt_historicoProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#Proceso", "Nombre", "Ragafa", "Quantum", "Tiempo Final", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_historicoProcesos.setEnabled(false);
        jScrollPane2.setViewportView(jt_historicoProcesos);
        if (jt_historicoProcesos.getColumnModel().getColumnCount() > 0) {
            jt_historicoProcesos.getColumnModel().getColumn(0).setResizable(false);
            jt_historicoProcesos.getColumnModel().getColumn(1).setResizable(false);
            jt_historicoProcesos.getColumnModel().getColumn(2).setResizable(false);
            jt_historicoProcesos.getColumnModel().getColumn(3).setResizable(false);
            jt_historicoProcesos.getColumnModel().getColumn(4).setResizable(false);
            jt_historicoProcesos.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("Tiempo de terminación de los procesos:");

        jTfTiempoTerminacion.setEditable(false);
        jTfTiempoTerminacion.setBackground(new java.awt.Color(225, 225, 237));
        jTfTiempoTerminacion.setBorder(null);
        jTfTiempoTerminacion.setEnabled(false);
        jTfTiempoTerminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfTiempoTerminacionActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(225, 225, 237));
        jTextField1.setBorder(null);
        jTextField1.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Tiempo promedio terminación del proceso:");

        jSRafaCPU.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbl_ragafaCPU)
                    .addComponent(jlb_nombreP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_nombreP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSRafaCPU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbl_canProceso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(jbl_timeProcesos))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_canProceso)
                            .addComponent(jTfTiempoTerminacion)
                            .addComponent(jTextField1)
                            .addComponent(jtf_TiempoEspera)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbl_proProceso)
                                .addGap(50, 50, 50)
                                .addComponent(jbl_porcentaje)
                                .addGap(69, 69, 69)
                                .addComponent(jbl_progreso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtf_proProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jtf_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBarraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(94, 94, 94))
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jbt_agregar)
                        .addGap(99, 99, 99)
                        .addComponent(jbt_iniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jbl_lisProcesos)))
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_nombreP)
                    .addComponent(jtf_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbl_ragafaCPU)
                    .addComponent(jSRafaCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_agregar)
                    .addComponent(jbt_iniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbl_lisProcesos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_proProceso)
                    .addComponent(jbl_porcentaje)
                    .addComponent(jbl_progreso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBarraProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_proProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbl_canProceso)
                            .addComponent(jtf_canProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTfTiempoTerminacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_timeProcesos)
                    .addComponent(jtf_TiempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombrePActionPerformed

    private void jtf_canProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_canProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_canProcesoActionPerformed

    private void jtf_TiempoEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_TiempoEsperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_TiempoEsperaActionPerformed

    private void jTfTiempoTerminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfTiempoTerminacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfTiempoTerminacionActionPerformed

    private void jbt_agregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_agregarMousePressed
        // TODO add your handling code here:
        jtf_nombreP.setText("");
        //jSRafaCPU
    }//GEN-LAST:event_jbt_agregarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcesarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcesarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcesarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcesarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcesarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar jBarraProgreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JSpinner jSRafaCPU;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTfTiempoTerminacion;
    private javax.swing.JLabel jbl_canProceso;
    private javax.swing.JLabel jbl_lisProcesos;
    private javax.swing.JLabel jbl_porcentaje;
    private javax.swing.JLabel jbl_proProceso;
    private javax.swing.JLabel jbl_progreso;
    private javax.swing.JLabel jbl_ragafaCPU;
    private javax.swing.JLabel jbl_timeProcesos;
    public javax.swing.JButton jbt_agregar;
    public javax.swing.JButton jbt_iniciar;
    private javax.swing.JLabel jlb_nombreP;
    public javax.swing.JTable jt_historicoProcesos;
    public javax.swing.JTable jtb_lisProcesos;
    public javax.swing.JTextField jtf_TiempoEspera;
    public javax.swing.JTextField jtf_canProceso;
    public javax.swing.JTextField jtf_nombreP;
    public javax.swing.JTextField jtf_porcentaje;
    public javax.swing.JTextField jtf_proProceso;
    private java.awt.Scrollbar scrollbar1;
    // End of variables declaration//GEN-END:variables
}
