/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author camilotr
 */
public class ProcesarGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProcesarGUI
     */
    public ProcesarGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_nombreP = new javax.swing.JLabel();
        jbl_ragafaCPU = new javax.swing.JLabel();
        jbl_quantum = new javax.swing.JLabel();
        jtf_nombreP = new javax.swing.JTextField();
        jtf_ragafaCPU = new javax.swing.JTextField();
        jtf_quantum = new javax.swing.JTextField();
        jbt_agregar = new javax.swing.JButton();
        jbt_iniciar = new javax.swing.JButton();
        jbl_lisProcesos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_lisProcesos = new javax.swing.JTable();
        jbl_proProceso = new javax.swing.JLabel();
        jbl_porcentaje = new javax.swing.JLabel();
        jbl_progreso = new javax.swing.JLabel();
        jtf_proProceso = new javax.swing.JTextField();
        jtf_porcentaje = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        jbl_canProceso = new javax.swing.JLabel();
        jbl_timeProcesos = new javax.swing.JLabel();
        jtf_canProceso = new javax.swing.JTextField();
        jtf_timeProcesos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);

        jlb_nombreP.setText("Nombre del proceso");

        jbl_ragafaCPU.setText("Rafaga del CPU");

        jbl_quantum.setText("Quantum");

        jtf_nombreP.setBackground(new java.awt.Color(225, 225, 237));
        jtf_nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombrePActionPerformed(evt);
            }
        });

        jtf_ragafaCPU.setBackground(new java.awt.Color(225, 225, 237));
        jtf_ragafaCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ragafaCPUActionPerformed(evt);
            }
        });

        jtf_quantum.setBackground(new java.awt.Color(225, 225, 237));

        jbt_agregar.setBackground(new java.awt.Color(251, 245, 245));
        jbt_agregar.setForeground(new java.awt.Color(0, 0, 153));
        jbt_agregar.setText("Agregar");

        jbt_iniciar.setBackground(new java.awt.Color(251, 245, 245));
        jbt_iniciar.setForeground(new java.awt.Color(153, 0, 0));
        jbt_iniciar.setText("Iniciar");

        jbl_lisProcesos.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jbl_lisProcesos.setForeground(new java.awt.Color(0, 0, 153));
        jbl_lisProcesos.setText("Lista De Procesos");

        jtb_lisProcesos.setBackground(new java.awt.Color(255, 245, 243));
        jtb_lisProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#Proceso", "Nombre", "Rafaga", "Quantum", "Residuo rafaga", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb_lisProcesos);
        if (jtb_lisProcesos.getColumnModel().getColumnCount() > 0) {
            jtb_lisProcesos.getColumnModel().getColumn(0).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(1).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(2).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(3).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(4).setResizable(false);
            jtb_lisProcesos.getColumnModel().getColumn(5).setResizable(false);
        }

        jbl_proProceso.setText("Proceso");

        jbl_porcentaje.setText("Porcentaje");

        jbl_progreso.setText("Progreso");

        jProgressBar1.setForeground(new java.awt.Color(0, 255, 0));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Historico Procesos");

        jbl_canProceso.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jbl_canProceso.setForeground(new java.awt.Color(0, 0, 204));
        jbl_canProceso.setText("Cantidad De Proceso");

        jbl_timeProcesos.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jbl_timeProcesos.setForeground(new java.awt.Color(255, 0, 0));
        jbl_timeProcesos.setText("Tiempo De Procesos");

        jtf_canProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_canProcesoActionPerformed(evt);
            }
        });

        jtf_timeProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_timeProcesosActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#Proceso", "Nombre", "Ragafa", "Quantum", "Tiempo Final", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jbt_agregar)
                        .addGap(99, 99, 99)
                        .addComponent(jbt_iniciar)
                        .addGap(190, 190, 190))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbl_quantum)
                            .addComponent(jbl_ragafaCPU)
                            .addComponent(jlb_nombreP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_ragafaCPU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_nombreP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_quantum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jbl_lisProcesos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbl_proProceso)
                                .addGap(50, 50, 50)
                                .addComponent(jbl_porcentaje)
                                .addGap(69, 69, 69)
                                .addComponent(jbl_progreso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtf_proProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jtf_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbl_canProceso)
                            .addComponent(jbl_timeProcesos))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_canProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_timeProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_nombreP)
                    .addComponent(jtf_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_ragafaCPU)
                    .addComponent(jtf_ragafaCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_quantum)
                    .addComponent(jtf_quantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_agregar)
                    .addComponent(jbt_iniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbl_lisProcesos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_proProceso)
                    .addComponent(jbl_porcentaje)
                    .addComponent(jbl_progreso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_proProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_canProceso)
                    .addComponent(jtf_canProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_timeProcesos)
                    .addComponent(jtf_timeProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombrePActionPerformed

    private void jtf_ragafaCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ragafaCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ragafaCPUActionPerformed

    private void jtf_canProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_canProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_canProcesoActionPerformed

    private void jtf_timeProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_timeProcesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_timeProcesosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcesarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcesarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcesarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcesarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcesarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jbl_canProceso;
    private javax.swing.JLabel jbl_lisProcesos;
    private javax.swing.JLabel jbl_porcentaje;
    private javax.swing.JLabel jbl_proProceso;
    private javax.swing.JLabel jbl_progreso;
    private javax.swing.JLabel jbl_quantum;
    private javax.swing.JLabel jbl_ragafaCPU;
    private javax.swing.JLabel jbl_timeProcesos;
    private javax.swing.JButton jbt_agregar;
    private javax.swing.JButton jbt_iniciar;
    private javax.swing.JLabel jlb_nombreP;
    private javax.swing.JTable jtb_lisProcesos;
    private javax.swing.JTextField jtf_canProceso;
    private javax.swing.JTextField jtf_nombreP;
    private javax.swing.JTextField jtf_porcentaje;
    private javax.swing.JTextField jtf_proProceso;
    private javax.swing.JTextField jtf_quantum;
    private javax.swing.JTextField jtf_ragafaCPU;
    private javax.swing.JTextField jtf_timeProcesos;
    // End of variables declaration//GEN-END:variables
}
